"""
v5_reasoning_chain.py — Ship Pro V5 推理链契约
唯一真相源：记录每个 Agent 阶段的推理过程与证据，用于审计和可回溯性。
"""
from __future__ import annotations

from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Dict, Any, Literal


class ExplorerFinding(BaseModel):
    """Explorer 发现的依赖关系，每条必须附带原文证据。"""

    dependency: str                         # 依赖描述，如 "COMP-001 → COMP-002"
    evidence: str                             # 必须引用原文（PRD / 文档片段）
    confidence: float = Field(..., ge=0.0, le=1.0)
    type: Literal["explicit", "inferred"]  # explicit = 原文明确提及；inferred = 推导

    model_config = {"extra": "forbid"}

    @field_validator("evidence")
    @classmethod
    def evidence_min_len(cls, v: str) -> str:
        if len(v.strip()) < 10:
            raise ValueError("Evidence must be at least 10 characters (must quote original text)")
        return v

    @field_validator("confidence")
    @classmethod
    def confidence_threshold(cls, v: float) -> float:
        if v < 0.5:
            raise ValueError("Confidence below 0.5 is too low; must increase evidence or re-examine")
        return v


class ArchitectRationale(BaseModel):
    """Architect 对每个工作包拆分的推理。"""

    wp_id: str
    rationale: str
    rejected_alternatives: List[str]          # 被否决的方案及其理由

    model_config = {"extra": "forbid"}

    @field_validator("rationale")
    @classmethod
    def not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("rationale must not be blank")
        return v

    @field_validator("rejected_alternatives")
    @classmethod
    def at_least_one_rejected(cls, v: List[str]) -> List[str]:
        if not v:
            raise ValueError("Must list at least one rejected alternative (design thinking evidence)")
        return v


class ReasoningChain(BaseModel):
    """完整推理链：从 Parser 到 AC Writer，每个阶段的关键决策与证据。"""

    parser: Dict[str, Any] = Field(
        default_factory=dict,
        description="Parser 阶段输出：结构化 PRD 树、解析异常、歧义列表",
    )
    explorer: Dict[str, Any] = Field(
        default_factory=dict,
        description="Explorer 阶段输出：发现列表、冲突报告、依赖图",
    )
    architect: Dict[str, Any] = Field(
        default_factory=dict,
        description="Architect 阶段输出：模块划分、工作包拆分、架构原则",
    )
    ac_writer: Optional[Dict[str, Any]] = Field(
        default=None,
        description="AC Writer 阶段输出：AC 列表、数值提取、验证方法",
    )
    chain_acknowledgment: Dict[str, Any] = Field(
        default_factory=dict,
        description="下游 Agent 确认已读取上游推理链的签章",
    )

    model_config = {"extra": "forbid"}

    @field_validator("chain_acknowledgment")
    @classmethod
    def ack_has_signature(cls, v: Dict[str, Any]) -> Dict[str, Any]:
        if "agent_name" not in v or "timestamp" not in v:
            raise ValueError("chain_acknowledgment must contain 'agent_name' and 'timestamp'")
        return v

    # 便捷方法：帮助下游 Agent 检查上游证据
    def explorer_findings(self) -> List[ExplorerFinding]:
        """从 explorer 字段提取标准化的 ExplorerFinding 列表。"""
        raw = self.explorer.get("findings", [])
        return [ExplorerFinding(**f) for f in raw if isinstance(f, dict)]

    def architect_rationales(self) -> List[ArchitectRationale]:
        """从 architect 字段提取标准化的 ArchitectRationale 列表。"""
        raw = self.architect.get("rationales", [])
        return [ArchitectRationale(**r) for r in raw if isinstance(r, dict)]

    def is_acknowledged(self) -> bool:
        """检查是否有下游 Agent 已确认读取。"""
        return bool(self.chain_acknowledgment.get("agent_name"))


# ── 自测 ──────────────────────────────────────────────────
if __name__ == "__main__":
    chain = ReasoningChain(
        parser={
            "prd_title": "Ship Pro V5",
            "total_sections": 8,
            "ambiguities": ["Section 3: 'high performance' is undefined"],
        },
        explorer={
            "findings": [
                {
                    "dependency": "COMP-001 → COMP-002",
                    "evidence": "PRD Section 2.1: 'The Parser shall output a structured tree consumed by the Explorer'",
                    "confidence": 0.95,
                    "type": "explicit",
                },
                {
                    "dependency": "COMP-003 → COMP-001",
                    "evidence": "PRD Section 4.3: 'The Architect must validate module boundaries against the requirement tree generated by the Parser'",
                    "confidence": 0.88,
                    "type": "inferred",
                },
            ],
            "conflicts": [],
        },
        architect={
            "rationales": [
                {
                    "wp_id": "WP-001",
                    "rationale": "Parser is a pure transformation layer with no external dependencies, making it the ideal first work package.",
                    "rejected_alternatives": [
                        "Merge Parser and Explorer into one WP (rejected: violates single responsibility)",
                        "Start with Explorer first (rejected: requires Parser output as input)",
                    ],
                },
            ],
            "principles": [{"name": "single_responsibility", "scope": "global"}],
        },
        ac_writer={
            "total_ac": 12,
            "numeric_ac": 5,
            "verification_methods": ["pytest", "benchmark", "manual_review"],
        },
        chain_acknowledgment={
            "agent_name": "Propagator",
            "timestamp": "2026-06-27T08:30:00Z",
            "read_sections": ["parser", "explorer", "architect"],
        },
    )
    print("✅ ReasoningChain validated, acknowledged by:", chain.chain_acknowledgment["agent_name"])
    print(f"   Explorer findings: {len(chain.explorer_findings())}")
    print(f"   Architect rationales: {len(chain.architect_rationales())}")
    print(f"   Acknowledged: {chain.is_acknowledged()}")

    # 低置信度测试
    try:
        ExplorerFinding(
            dependency="A → B",
            evidence="short",
            confidence=0.3,
            type="inferred",
        )
    except Exception as e:
        print(f"✅ Low confidence blocked: {e}")

    # 缺少 ack 签名测试
    try:
        ReasoningChain(chain_acknowledgment={})
    except Exception as e:
        print(f"✅ Missing ack signature blocked: {e}")

    print("\n🎉 v5_reasoning_chain.py 所有自测通过")
